
name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: lap 
    environment: Staging

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      # with:
      #   fetch-depth: 0

    # # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    # - name: Setup MSBuild.exe
    #   uses: microsoft/setup-msbuild@v2

    # # Execute all unit tests in the solution
    # - name: Execute unit tests
    #   run: dotnet test

    # # Restore the application to populate the obj folder with RuntimeIdentifiers
    # - name: Restore the application
    #   run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
    #   env:
    #     Configuration: ${{ matrix.configuration }}

    # Remove the pfx
    - name: Run the batch file
      shell: cmd
      run: run.bat
  
  email:
    needs: build
    runs-on: lap

    steps:
    # Send the generated file in email
    - name: Send email
      uses: dawidd6/action-send-mail@v3.12.0
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL }}
        password: ${{ secrets.PASSWORD }}
        subject: 'Test email'
        body: 'This is a test email'
        to: ${{ vars.EMAIL_TO }}
        from: ${{ secrets.EMAIL }}
        priority: 'normal'
        attachments: 'myfile.txt'
