
name: DCS WTUT DevOps Workflow test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check_username:
    runs-on: windows-latest
    outputs:
      username_match: ${{ steps.check_username.outputs.username_match }}
    steps:
      - name: Check if current username is in the list
        id: check_username
        shell: cmd
        run: |
          setlocal enabledelayedexpansion
          set "USERNAME=%GITHUB_ACTOR%"
          set "USERNAME_LIST=${{ vars.USERNAMES}}"
          for %%u in (%USERNAME_LIST%) do (
            if /I "%%u"=="%USERNAME%" (
              echo Current username is in the list
              set "USERNAME_MATCH=true"
            )
          )
          if not defined USERNAME_MATCH (
            echo Current username is not in the list
            set "USERNAME_MATCH=false"
          )
          echo "username_match=!USERNAME_MATCH!" >> $GITHUB_OUTPUT
          echo username_match=!USERNAME_MATCH! >> $GITHUB_OUTPUT

      - name: Set output
        run: echo "username_match=${{ steps.check_username.outputs.username_match }}"

  build:
    needs: check_username
    if: ${{ needs.check_username.outputs.username_match == 'true' }}
    runs-on: lap 
    environment: Staging

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Remove the pfx
    - name: Run the batch file
      shell: cmd
      run: run.bat
  
  email:
    needs: build
    runs-on: lap

    steps:
    # Send the generated file in email
    - name: Send email
      uses: dawidd6/action-send-mail@v3.12.0
      with:
        server_address: smtp.gmail.com
        server_port: 587
        username: ${{ secrets.EMAIL }}
        password: ${{ secrets.PASSWORD }}
        subject: 'Test email'
        body: 'This is a test email'
        to: ${{ vars.EMAIL_TO }}
        from: ${{ secrets.EMAIL }}
        priority: 'normal'
        attachments: 'myfile.txt'
